apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: androidsdks.androidsdk.aerogear.org
spec:
  group: androidsdk.aerogear.org
  names:
    kind: AndroidSDK
    listKind: AndroidSDKList
    plural: androidsdks
    singular: androidsdk
  scope: Namespaced
  version: v1